
Generate an Ansible playbook to change the hostname of a Red Hat server.
The playbook should:
1. Use the `hostname` module to set the hostname.
2. Update the `/etc/hostname` file.
3. Update the `/etc/hosts` file to map the hostname to the loopback address (127.0.0.1).
Provide the playbook in YAML format.

The playbook should be named `hostname.yml`.

## Solution

```yaml
---
- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update the hostname in /etc/hostname
  file:
    path: /etc/hostname
    state: present
    mode: 644

- name: Update the hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    mode: 644
```
