
Generate an Ansible playbook to change the hostname of a Red Hat server.
The playbook should:
1. Use the `hostname` module to set the hostname.
2. Update the `/etc/hostname` file.
3. Update the `/etc/hosts` file to map the hostname to the loopback address (127.0.0.1).
Provide the playbook in YAML format.

```yaml
---
- hosts: all
  become: true
  vars:
    new_hostname: 'new_hostname'
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ new_hostname }}"
      delegate_to: localhost
    - name: Update /etc/hostname
      file:
        path: /etc/hostname
        state: present
        backup: no
      delegate_to: localhost
    - name: Update /etc/hosts
      file:
        path: /etc/hosts
        state: present
        backup: no
      delegate_to: localhost
```
