
Generate an Ansible playbook to set the hostname of an IOS-XE network device.
The playbook should:
1. Use the `ios_config` module to set the hostname.
2. Ensure the configuration is saved to the device.
Provide the playbook in YAML format.

### Setup

Create an inventory file called `inventory.yml` with the following:
```
[ios_devices]
ios_device1
ios_device2
ios_device3
```

### Solution

1. Include the `ios_config` module in the playbook.
2. Set the hostname of the device.
3. Ensure the configuration is saved to the device.

```yaml
---
- hosts: ios_devices
  vars:
    hostname: "{{ inventory_hostname }}"
  tasks:
    - name: Set hostname
      ios_config:
        hostname: