
Generate an Ansible playbook to set the hostname of an IOS-XE network device.
The playbook should:
1. Use the `ios_config` module to set the hostname.
2. Ensure the configuration is saved to the device.
Provide the playbook in YAML format.

### Example Playbook

```
---
- hosts: ioxe
  gather_facts: no
  vars:
    ios_hostname: "{{ inventory_hostname }}-ios"

  tasks:
    - name: Set the hostname
      ios_config:
        hostname: "{{ ios_hostname }}"
      delegate_to: localhost
```

### Expected Playbook Output

```
TASK [Set the hostname]
ok: [iodev]
```

### Example Playbook with Inventory

```
---
- hosts: ioxe
  gather_facts: no
